# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."nginx-proxy-manager-app" = {
    image = "jc21/nginx-proxy-manager:latest";
    environment = {
      "TZ" = "Australia/Brisbane";
    };
    volumes = [
      "nginx-proxy-manager_data:/data:rw"
      "nginx-proxy-manager_letsencrypt:/etc/letsencrypt:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-nginx-proxy-manager-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-volume-nginx-proxy-manager_data.service"
      "podman-volume-nginx-proxy-manager_letsencrypt.service"
    ];
    requires = [
      "podman-volume-nginx-proxy-manager_data.service"
      "podman-volume-nginx-proxy-manager_letsencrypt.service"
    ];
    partOf = [
      "podman-compose-nginx-proxy-manager-root.target"
    ];
    wantedBy = [
      "podman-compose-nginx-proxy-manager-root.target"
    ];
  };

  # Volumes
  systemd.services."podman-volume-nginx-proxy-manager_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect nginx-proxy-manager_data || podman volume create nginx-proxy-manager_data
    '';
    partOf = [ "podman-compose-nginx-proxy-manager-root.target" ];
    wantedBy = [ "podman-compose-nginx-proxy-manager-root.target" ];
  };
  systemd.services."podman-volume-nginx-proxy-manager_letsencrypt" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect nginx-proxy-manager_letsencrypt || podman volume create nginx-proxy-manager_letsencrypt
    '';
    partOf = [ "podman-compose-nginx-proxy-manager-root.target" ];
    wantedBy = [ "podman-compose-nginx-proxy-manager-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nginx-proxy-manager-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
